### ISSUE TITLE
The config seems to have a typo.

### ISSUE THREAD

**Issue by Run542968** [ZMHH-H/MoTE#1]
There are some duplicate keywords, e.g. `val_root`.
https://github.com/ZMHH-H/MoTE/blob/cc853b03db6d2dc95c3ec49704e1e2d5f20c0eb9/configs/k400/k400_train_video_vitb-16-f8.yaml#L13C17-L13C26

**Comment by ZMHH-H** [comment]
Thanks for your reminder. We have fixed the typo.
